name: Rails CI

on:
  push:
    branches:
      - main  # main ブランチにプッシュされた場合に実行
  pull_request:
    branches:
      - main  # main ブランチへのプルリクエストが作成された場合に実行

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.5'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Set up database
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rake db:create db:schema:load
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/myapp_test

      - name: Run tests
        run: |
          bundle exec rake test
